

trigger:
- none

pool: aks_pool

stages:
- stage: buildstage
  displayName: build-stage
  jobs:
  - job: buildjob
    displayName: build-job
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-connection'
        repository: 'first'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
       

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'manifests'
        Contents: '*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'
 
- stage: deployStage
  displayName: deployStage
  jobs:
    
    -  deployment: deploy
       environment: dev
       strategy:
        runOnce:
            deploy:
                steps:
                - download: current
                  artifact: manifests
              
                - task: KubernetesManifest@1
                  inputs:
                    action: 'deploy'
                    connectionType: 'kubernetesServiceConnection'
                    kubernetesServiceConnection: 'k8s-connection'
                    manifests: '$(Pipeline.Workspace)/manifests/*.yaml'
                    containers: 'sam15.azurecr.io/first:$(Build.BuildId)'


                
                
               

    
        




